# -*- coding: utf-8 -*-
"""fashion-mnist-gan-image-generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpvVklxC4xAyMAccXAlc7TrNACwwwwZy
"""

import os
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU, Reshape, Flatten, Dropout
from tensorflow.keras.optimizers import Adam

tf.keras.backend.clear_session()

np.random.seed(42)
tf.random.set_seed(42)

desktop_path = "."

# Load data
(x_train, y_train), (_, _) = fashion_mnist.load_data()

# Keep only ankle boot
x_train = x_train[y_train == 9]

# Normalize to [-1, 1]
x_train = x_train.astype("float32")
x_train = (x_train - 127.5) / 127.5
x_train = np.expand_dims(x_train, axis=-1)

print("x_train shape:", x_train.shape)

noise_dim = 100
img_shape = (28, 28, 1)

# Generator
generator = Sequential([
    Dense(256, input_shape=(noise_dim,)),
    LeakyReLU(negative_slope=0.2),

    Dense(512),
    LeakyReLU(negative_slope=0.2),

    Dense(1024),
    LeakyReLU(negative_slope=0.2),

    Dense(28 * 28 * 1, activation="tanh"),
    Reshape(img_shape)
])

# Discriminator
discriminator = Sequential([
    Flatten(input_shape=img_shape),

    Dense(512),
    LeakyReLU(negative_slope=0.2),
    Dropout(0.3),

    Dense(256),
    LeakyReLU(negative_slope=0.2),
    Dropout(0.3),

    Dense(1, activation="sigmoid")
])

# Compile discriminator
discriminator.trainable = True
discriminator.compile(
    loss="binary_crossentropy",
    optimizer=Adam(learning_rate=0.0001, beta_1=0.5),
    metrics=["accuracy"]
)

# Build GAN
discriminator.trainable = False

gan = Sequential([
    generator,
    discriminator
])

gan.compile(
    loss="binary_crossentropy",
    optimizer=Adam(learning_rate=0.0002, beta_1=0.5)
)

fixed_noise = np.random.normal(0, 1, (16, noise_dim))


def save_generated_images(epoch):
    generated_images = generator(fixed_noise, training=False).numpy()
    generated_images = 0.5 * generated_images + 0.5

    plt.figure(figsize=(4, 4))

    for i in range(16):
        plt.subplot(4, 4, i + 1)
        plt.imshow(generated_images[i, :, :, 0], cmap="gray")
        plt.axis("off")

    plt.suptitle(f"Epoch {epoch}")
    plt.tight_layout()

    save_path = os.path.join(desktop_path, f"fixed_gan_boot_epoch_{epoch}.png")
    plt.savefig(save_path)
    plt.close()

    print("Image saved:", save_path)


epochs = 10000
batch_size = 64
sample_interval = 500

for epoch in range(epochs + 1):

    # -------------------------
    # 1) Train Discriminator
    # -------------------------
    discriminator.trainable = True

    idx = np.random.randint(0, x_train.shape[0], batch_size)
    real_images = x_train[idx]

    noise = np.random.normal(0, 1, (batch_size, noise_dim))
    fake_images = generator(noise, training=False).numpy()

    real_labels = np.ones((batch_size, 1)) * 0.9
    fake_labels = np.zeros((batch_size, 1))

    d_loss_real = discriminator.train_on_batch(real_images, real_labels)
    d_loss_fake = discriminator.train_on_batch(fake_images, fake_labels)

    d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

    # -------------------------
    # 2) Train Generator
    # -------------------------
    discriminator.trainable = False

    noise = np.random.normal(0, 1, (batch_size, noise_dim))
    valid_labels = np.ones((batch_size, 1))

    g_loss = gan.train_on_batch(noise, valid_labels)

    # -------------------------
    # 3) Save progress
    # -------------------------
    if epoch % sample_interval == 0:
        print(
            f"Epoch {epoch} | "
            f"D loss: {d_loss[0]:.4f}, acc: {d_loss[1]:.4f} | "
            f"G loss: {g_loss:.4f}"
        )

        save_generated_images(epoch)

generator.save(os.path.join(desktop_path, "fixed_gan_boot_generator.keras"))

print("Training finished.")

