# -*- coding: utf-8 -*-
<<<<<<< HEAD
"""fashion_mnist_gan
=======
"""fashion-mnist-gan-image-generation
>>>>>>> fc0eaa2756ffb29bcea6a52ffa2ed0e39ce2bf1f

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpvVklxC4xAyMAccXAlc7TrNACwwwwZy
"""

import os
<<<<<<< HEAD
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LeakyReLU,Reshape,Flatten,Dropout
from tensorflow.keras.optimizers import Adam

tf.keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

project_dir="."
image_dir=os.path.join(project_dir,"generated_image")
model_dir=os.path.join(project_dir,"models")

os.makedirs(image_dir,exist_ok=True)
os.makedirs(model_dir,exist_ok=True)

noise_dim=100
img_shape=(28,28,1)

noise_dim=100
img_shape=(28,28,1)

(x_train, y_train), (_, _) = fashion_mnist.load_data()
x_train=x_train[y_train==9]

x_train=x_train.astype("float32")
x_train=(x_train-127.5)/127.5

x_train=np.expand_dims(x_train,axis=-1)

print("Training images shape:", x_train.shape)
print("Minimum pixel value:", x_train.min())
print("Maximum pixel value:", x_train.max())

def build_generator(noise_dim, img_shape):
    model = Sequential(name="Generator")

    model.add(Dense(256, input_shape=(noise_dim,)))
    model.add(LeakyReLU(negative_slope=0.2))

    model.add(Dense(512))
    model.add(LeakyReLU(negative_slope=0.2))

    model.add(Dense(1024))
    model.add(LeakyReLU(negative_slope=0.2))

    model.add(Dense(28 * 28 * 1, activation="tanh"))
    model.add(Reshape(img_shape))

    return model


generator = build_generator(noise_dim, img_shape)
generator.summary()

def build_discriminator(img_shape):
  model=Sequential(name="discriminator")
  model.add(Flatten(input_shape=img_shape))
  model.add(Dense(512))
  model.add(LeakyReLU(negative_slope=0.2))
  model.add(Dropout(0.3))

  model.add(Dense(256))
  model.add(LeakyReLU(negative_slope=0.2))
  model.add(Dropout(0.3))

  model.add(Dense(1, activation="sigmoid"))

  return model

discriminator = build_discriminator(img_shape)

=======
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU, Reshape, Flatten, Dropout
from tensorflow.keras.optimizers import Adam

tf.keras.backend.clear_session()

np.random.seed(42)
tf.random.set_seed(42)

desktop_path = "."

# Load data
(x_train, y_train), (_, _) = fashion_mnist.load_data()

# Keep only ankle boot
x_train = x_train[y_train == 9]

# Normalize to [-1, 1]
x_train = x_train.astype("float32")
x_train = (x_train - 127.5) / 127.5
x_train = np.expand_dims(x_train, axis=-1)

print("x_train shape:", x_train.shape)

noise_dim = 100
img_shape = (28, 28, 1)

# Generator
generator = Sequential([
    Dense(256, input_shape=(noise_dim,)),
    LeakyReLU(negative_slope=0.2),

    Dense(512),
    LeakyReLU(negative_slope=0.2),

    Dense(1024),
    LeakyReLU(negative_slope=0.2),

    Dense(28 * 28 * 1, activation="tanh"),
    Reshape(img_shape)
])

# Discriminator
discriminator = Sequential([
    Flatten(input_shape=img_shape),

    Dense(512),
    LeakyReLU(negative_slope=0.2),
    Dropout(0.3),

    Dense(256),
    LeakyReLU(negative_slope=0.2),
    Dropout(0.3),

    Dense(1, activation="sigmoid")
])

# Compile discriminator
discriminator.trainable = True
>>>>>>> fc0eaa2756ffb29bcea6a52ffa2ed0e39ce2bf1f
discriminator.compile(
    loss="binary_crossentropy",
    optimizer=Adam(learning_rate=0.0001, beta_1=0.5),
    metrics=["accuracy"]
)

<<<<<<< HEAD
discriminator.summary()

def build_gan(generator, discriminator):
    discriminator.trainable = False

    model = Sequential(name="GAN")
    model.add(generator)
    model.add(discriminator)

    model.compile(
        loss="binary_crossentropy",
        optimizer=Adam(learning_rate=0.0002, beta_1=0.5)
    )

    return model


gan = build_gan(generator, discriminator)
gan.summary()

fixed_noise=np.random.normal(0,1,(16,noise_dim))

def saved_generated_images(generator,epoch):
  generated_images=generator(fixed_noise,training=False).numpy()
  generated_images=0.5*generated_images+0.5
  plt.figure(figsize=(4,4))
  for i in range(16):
    plt.subplot(4,4,i+1)
    plt.imshow(generated_images[i,:,:0],cmap="gray")
  plt.suptitle(f"Epoch {epoch}")
  plt.tight_layout()

  save_path = os.path.join(image_dir, f"epoch_{epoch}.png")
  plt.savefig(save_path)
  plt.close()

  print("Image saved:", save_path)

fixed_noise=np.random.normal(0,1,(16,noise_dim))

def saved_generated_images(generator,epoch):
  generated_images=generator(fixed_noise,training=False).numpy()
  generated_images=0.5*generated_images+0.5
  plt.figure(figsize=(4,4))
  for i in range(16):
    plt.subplot(4,4,i+1)
    plt.imshow(generated_images[i,:,:0],cmap="gray")
  plt.suptitle(f"Epoch {epoch}")
  plt.tight_layout()

  save_path = os.path.join(image_dir, f"epoch_{epoch}.png")
  plt.savefig(save_path)
  plt.close()

  print("Image saved:", save_path)

def train_gan(generator, discriminator, gan, x_train, epochs=10000, batch_size=64, sample_interval=500):

    for epoch in range(epochs + 1):


        discriminator.trainable = True

        idx = np.random.randint(0, x_train.shape[0], batch_size)
        real_images = x_train[idx]

        noise = np.random.normal(0, 1, (batch_size, noise_dim))
        fake_images = generator(noise, training=False).numpy()

        real_labels = np.ones((batch_size, 1)) * 0.9
        fake_labels = np.zeros((batch_size, 1))

        d_loss_real = discriminator.train_on_batch(real_images, real_labels)
        d_loss_fake = discriminator.train_on_batch(fake_images, fake_labels)

        d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)


        discriminator.trainable = False

        noise = np.random.normal(0, 1, (batch_size, noise_dim))
        valid_labels = np.ones((batch_size, 1))

        g_loss = gan.train_on_batch(noise, valid_labels)


        if epoch % sample_interval==0:



          print(
          f"Epoch {epoch} | "
          f"D loss: {d_loss[0]:.4f}, acc: {d_loss[1]:.4f} | "
          f"G loss: {g_loss:.4f}"
    )

    saved_generated_images(generator, epoch)

train_gan(
    generator=generator,
    discriminator=discriminator,
    gan=gan,
    x_train=x_train,
    epochs=10000,
    batch_size=64,
    sample_interval=500
)

generator.save(os.path.join(model_dir, "ankle_boot_generator.keras"))

print("Training finished.")
=======
# Build GAN
discriminator.trainable = False

gan = Sequential([
    generator,
    discriminator
])

gan.compile(
    loss="binary_crossentropy",
    optimizer=Adam(learning_rate=0.0002, beta_1=0.5)
)

fixed_noise = np.random.normal(0, 1, (16, noise_dim))


def save_generated_images(epoch):
    generated_images = generator(fixed_noise, training=False).numpy()
    generated_images = 0.5 * generated_images + 0.5

    plt.figure(figsize=(4, 4))

    for i in range(16):
        plt.subplot(4, 4, i + 1)
        plt.imshow(generated_images[i, :, :, 0], cmap="gray")
        plt.axis("off")

    plt.suptitle(f"Epoch {epoch}")
    plt.tight_layout()

    save_path = os.path.join(desktop_path, f"fixed_gan_boot_epoch_{epoch}.png")
    plt.savefig(save_path)
    plt.close()

    print("Image saved:", save_path)


epochs = 10000
batch_size = 64
sample_interval = 500

for epoch in range(epochs + 1):

    # -------------------------
    # 1) Train Discriminator
    # -------------------------
    discriminator.trainable = True

    idx = np.random.randint(0, x_train.shape[0], batch_size)
    real_images = x_train[idx]

    noise = np.random.normal(0, 1, (batch_size, noise_dim))
    fake_images = generator(noise, training=False).numpy()

    real_labels = np.ones((batch_size, 1)) * 0.9
    fake_labels = np.zeros((batch_size, 1))

    d_loss_real = discriminator.train_on_batch(real_images, real_labels)
    d_loss_fake = discriminator.train_on_batch(fake_images, fake_labels)

    d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

    # -------------------------
    # 2) Train Generator
    # -------------------------
    discriminator.trainable = False

    noise = np.random.normal(0, 1, (batch_size, noise_dim))
    valid_labels = np.ones((batch_size, 1))

    g_loss = gan.train_on_batch(noise, valid_labels)

    # -------------------------
    # 3) Save progress
    # -------------------------
    if epoch % sample_interval == 0:
        print(
            f"Epoch {epoch} | "
            f"D loss: {d_loss[0]:.4f}, acc: {d_loss[1]:.4f} | "
            f"G loss: {g_loss:.4f}"
        )

        save_generated_images(epoch)

generator.save(os.path.join(desktop_path, "fixed_gan_boot_generator.keras"))

print("Training finished.")

>>>>>>> fc0eaa2756ffb29bcea6a52ffa2ed0e39ce2bf1f
